---
- name: playbook to install elinks, git, maven, tree, tomcat9, tomcat9-admin
  hosts: all
  become: true
  tasks:
   - name: install elinks
     apt: 
       name: elinkasdfs
       state: present
   - name: install git
     apt: 
       name: git
       state: present
     tags: 
       - install_git
   - name: install maven
     apt: 
       name: maven
       state: present
   - name: install tree
     apt: 
       name: tree
       state: present
     tags: 
       - install_tree
   - name: install tomcat9
     apt: 
       name: tomcat9
       state: present
   - name: install tomcat9-admin
     apt: 
       name: tomcat9
       state: present
...
