---
- name: Update the password of a user account if the user account already exists
  hosts: all
  become: true
  tasks:
   - name: create a user
     user: 
       name: puru
     register: result
   - name: print the output of the above play
     debug:
       var: result
   - name: update the password of the user
     user: 
       name: puru
       password: 123456
     when:
      result.changed==false
...
