---
- name: Variables example
  hosts: 172.31.83.34
  become: true
  tasks:
   - name: create a user
     user:
      name: "{{myname}}"
      password: "{{mypass}}"
      home: "{{myhome}}"
      comment: "{{mydesg}}" 
      uid: "{{myuid}}"
   - name: create a file in user's workspace
     file:
      name: "{{myfile}}"
      state: "{{mystat}}"
   - name: create a directory
     file:
      name: "{{mydir}}"
      state: "{{mystat2}}"
...
