---
- name: playscope variables
  hosts: all
  become: true
  vars: 
    - var1: maven
    - var2: present
    - var3: yes
    - var4: 200
  tasks:
   - name: 
     apt: 
       name: "{{var1}}"
       state: "{{var2}}"
       update_cache: "{{var3}}"
     when:
       var4==200
...
