---
- name: interactive inputs
  hosts: all
  become: true
  vars_prompt:
   - name: username
     prompt: what is yourname?
     private: no
   - name: filename
     prompt: what is your filename?
     private: no
  tasks:
   - name: create a user
     user: 
      name: "{{username}}"
   - name: create a file
     file: 
       name: /home/ubuntu/"{{filename}}"
       state: touch

...
